name: Build Complete AX4200Q with Full QoS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 python3-requests
        
    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.3
        
    - name: Configure for AX4200Q with full QoS
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 创建包含完整QoS的配置
        cat > .config << 'EOF'
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_asus_tuf-ax4200=y

# 基础系统
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-theme-argon=y

# 完整QoS支持
CONFIG_PACKAGE_luci-app-qos=y
CONFIG_PACKAGE_qos-scripts=y
CONFIG_PACKAGE_kmod-sched-cake=y
CONFIG_PACKAGE_kmod-sched-htb=y
CONFIG_PACKAGE_kmod-sched-core=y
CONFIG_PACKAGE_kmod-ifb=y
CONFIG_PACKAGE_iptables-mod-filter=y
CONFIG_PACKAGE_iptables-mod-ipopt=y
CONFIG_PACKAGE_tc-full=y

# 网络驱动
CONFIG_PACKAGE_kmod-mt7915e=y
CONFIG_PACKAGE_kmod-mt7916-firmware=y
CONFIG_PACKAGE_kmod-usb-core=y
CONFIG_PACKAGE_kmod-usb2=y
CONFIG_PACKAGE_kmod-usb3=y

# 工具
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_iperf3=y

# 中文支持
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
CONFIG_PACKAGE_luci-i18n-qos-zh-cn=y
EOF

        make defconfig
        
    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc)
        
    - name: Upload complete firmware
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-ax4200q-full-qos
        path: openwrt/bin/targets/mediatek/filogic/*.bin
