name: Build Complete AX4200Q Firmware

on:
  workflow_dispatch:
    inputs:
      kernel_modules:
        description: 'Additional kernel modules'
        required: false
        default: 'kmod-sched-cake kmod-sched-core kmod-ifb iptables-mod-filter iptables-mod-ipopt'

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Clone OpenWrt source with AX4200 support
      run: |
        # 使用官方 OpenWrt，因为对 AX4200 支持更好
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        # 使用最新稳定版本
        git checkout v23.05.3
        
    - name: Setup build environment
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 安装编译依赖
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 python3-requests
        
    - name: Apply AX4200Q specific configuration
      run: |
        cd openwrt
        
        # 创建针对 AX4200Q 的配置
        cat > .config << 'EOF'
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_asus_tuf-ax4200=y

# 基础系统
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-theme-argon=y

# QoS 完整支持
CONFIG_PACKAGE_luci-app-qos=y
CONFIG_PACKAGE_qos-scripts=y
CONFIG_PACKAGE_kmod-sched-cake=y
CONFIG_PACKAGE_kmod-sched-core=y
CONFIG_PACKAGE_kmod-sched-connmark=y
CONFIG_PACKAGE_kmod-ifb=y
CONFIG_PACKAGE_iptables-mod-filter=y
CONFIG_PACKAGE_iptables-mod-ipopt=y
CONFIG_PACKAGE_tc-full=y
CONFIG_PACKAGE_kmod-nf-conntrack=y

# 网络基础
CONFIG_PACKAGE_kmod-mt7915e=y  # 无线驱动
CONFIG_PACKAGE_kmod-mt7916-firmware=y
CONFIG_PACKAGE_kmod-usb-core=y
CONFIG_PACKAGE_kmod-usb-ohci=y
CONFIG_PACKAGE_kmod-usb2=y
CONFIG_PACKAGE_kmod-usb3=y

# 工具
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_iperf3=y
CONFIG_PACKAGE_tcpdump=y

# 中文支持
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
CONFIG_PACKAGE_luci-i18n-qos-zh-cn=y
EOF

        # 应用配置
        make defconfig
        
    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc)
        
    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-ax4200q-complete
        path: openwrt/bin/targets/mediatek/filogic/*.bin
        retention-days: 30
