name: Build ImmortalWrt for AX4200Q with QoS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 python3-requests
        
    - name: Clone ImmortalWrt
      run: |
        git clone https://github.com/immortalwrt/immortalwrt.git
        cd immortalwrt
        git checkout master
        
    - name: Configure with full QoS
      run: |
        cd immortalwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 使用 menuconfig 或创建配置
        make menuconfig
        # 在这里手动选择：
        # - Target: MediaTek Ralink MIPS → MT7986 filogic
        # - Device: ASUS TUF-AX4200
        # - 选择所有 QoS 相关包
        
    - name: Build
      run: |
        cd immortalwrt
        make -j$(nproc)
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-ax4200q-full
        path: immortalwrt/bin/targets/mediatek/filogic/*.bin
