name: Build ImmortalWrt for AX4200Q

on:
  workflow_dispatch:
    inputs:
      extra_packages:
        description: 'Extra packages (e.g., luci-app-qos luci-app-upnp)'
        required: false
        default: 'luci-app-qos luci-app-upnp luci-app-wol'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 python3-requests
          
    - name: Download and extract ImageBuilder
      run: |
        wget https://downloads.immortalwrt.org/releases/23.05.4/targets/mediatek/filogic/immortalwrt-imagebuilder-23.05.4-mediatek-filogic.Linux-x86_64.tar.xz
        tar -xf immortalwrt-imagebuilder-23.05.4-mediatek-filogic.Linux-x86_64.tar.xz
        cd immortalwrt-imagebuilder-23.05.4-mediatek-filogic.Linux-x86_64
        
    - name: Build firmware with essential packages
      run: |
        cd immortalwrt-imagebuilder-23.05.4-mediatek-filogic.Linux-x86_64
        make image PROFILE="asus_tuf-ax4200q" \
          PACKAGES="luci luci-compat luci-theme-argon ${{ github.event.inputs.extra_packages }}"
        
    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: ax4200q-firmware
        path: |
          immortalwrt-imagebuilder-23.05.4-mediatek-filogic.Linux-x86_64/bin/targets/mediatek/filogic/*.bin
        retention-days: 30
