name: Debug AX4200Q Build

on:
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 python3-requests
        echo "✅ 基础依赖安装完成"
        
    - name: Test network connectivity
      run: |
        echo "测试网络连接..."
        ping -c 3 git.openwrt.org || echo "ping失败，但继续"
        wget --spider https://git.openwrt.org/openwrt/openwrt.git
        echo "✅ 网络测试完成"
        
    - name: Clone OpenWrt source (with retry)
      run: |
        for i in {1..3}; do
          echo "尝试第 $i 次克隆..."
          if git clone --depth=1 https://git.openwrt.org/openwrt/openwrt.git; then
            echo "✅ 克隆成功"
            break
          else
            echo "❌ 克隆失败，清理后重试..."
            rm -rf openwrt
            sleep 10
          fi
        done
        
        if [ ! -d "openwrt" ]; then
          echo "❌ 所有克隆尝试都失败"
          exit 1
        fi
        
        cd openwrt
        git checkout v23.05.3
        echo "✅ 源码准备完成"
        
    - name: Setup feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        echo "✅ Feeds 更新完成"
        
    - name: Simple configuration test
      run: |
        cd openwrt
        # 只配置基本目标，不包含具体包
        cat > .config << 'EOF'
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_asus_tuf-ax4200=y
CONFIG_PACKAGE_luci=y
EOF
        
        make defconfig
        echo "✅ 基础配置测试完成"
        
    - name: Build test (10 minutes timeout)
      timeout-minutes: 10
      run: |
        cd openwrt
        echo "开始编译测试（10分钟超时）..."
        make -j2
