name: Build AX4200Q with QoS

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3
        
    - name: Clone OpenWrt
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.3
        
    - name: Configure and build
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 使用 menuconfig 的预设配置
        make menuconfig <<< ""

        # 强制包含必要的包
        echo "CONFIG_TARGET_mediatek=y" >> .config
        echo "CONFIG_TARGET_mediatek_filogic=y" >> .config  
        echo "CONFIG_TARGET_mediatek_filogic_DEVICE_asus_tuf-ax4200=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-qos=y" >> .config
        echo "CONFIG_PACKAGE_qos-scripts=y" >> .config
        echo "CONFIG_PACKAGE_kmod-sched-cake=y" >> .config
        
        make defconfig
        make -j$(nproc)
        
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: ax4200q-firmware
        path: openwrt/bin/targets/mediatek/filogic/*.bin
